# Generated by Django 4.0.5 on 2022-09-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_person_foodcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default='uploads_avatar/default.png', upload_to='uploads_avatar/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
