# Generated by Django 4.0.5 on 2022-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_foodcart_isorder_person_avatar_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
