# Generated by Django 4.0.5 on 2022-11-02 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_foodorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='timeOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
