# Generated by Django 4.0.5 on 2022-11-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_foodorder_timeorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='timeUpload',
        ),
    ]
