# Generated by Django 4.0.5 on 2022-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_remove_food_timeupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
