# Generated by Django 4.0.5 on 2022-11-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_foodcart_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
