# Generated by Django 4.0.5 on 2022-11-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_foodorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='phoneOrder',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
