# Generated by Django 4.0.5 on 2022-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_food_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='isCancel',
            field=models.BooleanField(default=False),
        ),
    ]
